## Redis library image
## ref: https://hub.docker.com/r/library/redis/
##
image:
  registry: docker.io
  repository: redis
  tag: '5.0.5'

primary:
  command: "redis-server"

replica:
  command: "redis-server"
