apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  redis.conf: |-
{{- if .Values.configmap }}
    # User-supplied configuration:
{{ tpl .Values.configmap . | indent 4 }}
{{- end }}
  primary.conf: |-
    dir {{ .Values.primary.persistence.path }}
{{- if .Values.primary.configmap }}
    # User-supplied primary configuration:
{{ tpl .Values.primary.configmap . | indent 4 }}
{{- end }}
{{- if .Values.primary.disableCommands }}
{{- range .Values.primary.disableCommands }}
    rename-command {{ . }} ""
{{- end }}
{{- end }}
  replica.conf: |-
    dir {{ .Values.replica.persistence.path }}
    replica-read-only yes
{{- if .Values.replica.configmap }}
    # User-supplied replica configuration:
{{ tpl .Values.replica.configmap . | indent 4 }}
{{- end }}
{{- if .Values.replica.disableCommands }}
{{- range .Values.replica.disableCommands }}
    rename-command {{ . }} ""
{{- end }}
{{- end }}
{{- if .Values.sentinel.enabled }}
  sentinel.conf: |-
    dir "/tmp"
    bind 0.0.0.0
    port {{ .Values.sentinel.port }}
    sentinel monitor {{ .Values.sentinel.primarySet }} {{ template "redis.fullname" . }}-primary-0.{{ template "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }} {{ .Values.redisPort }} {{ .Values.sentinel.quorum }}
    sentinel down-after-milliseconds {{ .Values.sentinel.primarySet }} {{ .Values.sentinel.downAfterMilliseconds }}
    sentinel failover-timeout {{ .Values.sentinel.primarySet }} {{ .Values.sentinel.failoverTimeout }}
    sentinel parallel-syncs {{ .Values.sentinel.primarySet }} {{ .Values.sentinel.parallelSyncs }}
{{- if .Values.sentinel.configmap }}
    # User-supplied sentinel configuration:
{{ tpl .Values.sentinel.configmap . | indent 4 }}
{{- end }}
{{- end }}
