{{- if and .Values.cluster.enabled (not .Values.sentinel.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}-replica
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.replica.service.labels -}}
    {{ toYaml .Values.replica.service.labels | nindent 4 }}
    {{- end -}}
{{- if .Values.replica.service.annotations }}
  annotations:
{{ toYaml .Values.replica.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.replica.service.type }}
  {{- if and (eq .Values.replica.service.type "LoadBalancer") .Values.replica.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.replica.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.replica.service.type "LoadBalancer") .Values.replica.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- with .Values.replica.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- end }}
  ports:
  - name: redis
    port: {{ .Values.replica.service.port }}
    targetPort: redis
    {{- if .Values.replica.service.nodePort }}
    nodePort: {{ .Values.replica.service.nodePort }}
    {{- end }}
  selector:
    app: {{ template "redis.name" . }}
    release: {{ .Release.Name }}
    role: replica
{{- end }}
